#!/usr/bin/env node
// Generates EVENT_GRAPH.md: machine-checked connection map of all V2 events —
// flags set/unlocked/blocked/required/altered per event, plus cross-pack ties.
// Run: node tools/event-graph.mjs   (CI: fails if graph is incoherent)
import { readFileSync, writeFileSync } from 'node:fs';
import { validateAll } from '../src/schema.mjs';

const load = p => JSON.parse(readFileSync(new URL(p, import.meta.url)));
const events = load('../src/events.json');
const extra = [];
try { extra.push(...load('../src/events-v2-content.json')); } catch {}
try {
  const q = await import('../src/branch-quebec-1995.mjs');
  extra.push(q.QUEBEC_1995_REFERENDUM_V2, ...q.QUEBEC_1995_BRANCH);
} catch {}
try {
  const s = await import('../src/pack-scandals.mjs');
  extra.push(...s.SCANDAL_PACK);
} catch {}
try {
  const sp = await import('../src/pack-indigenous-spine.mjs');
  extra.push(...sp.INDIGENOUS_SPINE);
} catch {}
try {
  const wb = await import('../src/pack-wheat-board.mjs');
  extra.push(...wb.WHEAT_BOARD_PACK);
} catch {}
try {
  const tr = await import('../src/pack-trade.mjs');
  extra.push(...tr.TRADE_PACK);
} catch {}
const all = [...events.filter(e => !extra.some(x => x.id === e.id)), ...extra];

const errors = validateAll(all);
if (errors.length) {
  console.error('GRAPH INVALID:\n' + errors.join('\n'));
  process.exit(1);
}

const byId = new Map(all.map(e => [e.id, e]));
const PACKS = {
  QUEBEC: ['QUEBEC_REFERENDUM_1980', 'QUEBEC_REFERENDUM_1995', 'QUEBEC_NEGOTIATION_1996'],
  SCANDAL: [], WHEAT: [], TRADE: [], NEP: [], SPINE: [], CROWN: [],
};

let md = `# V2 Event Graph — connections & dependencies

*Generated by tools/event-graph.mjs. Do not edit by hand.*

Every arrow below is enforced by CI (\`npm run check\` extends here): an unlock,
block, or alter referencing a missing event id fails validation. Flags named
\`sets:\` are durable world state; \`requires:\` gates eligibility.

`;

for (const e of all) {
  const lines = [];
  if (e.needsUnlock) lines.push(`- **needs unlock** to become eligible`);
  for (const r of e.requires || []) lines.push(`- requires: \`${r}\``);
  for (const c of e.choices) {
    const bits = [];
    if (c.setsFlags && Object.keys(c.setsFlags).length) bits.push(`sets ${Object.entries(c.setsFlags).map(([k,v]) => `\`${k}=${v}\``).join(', ')}`);
    if (c.unlocks?.length) bits.push(`unlocks ${c.unlocks.map(u => `**${u}**`).join(', ')}`);
    if (c.blocks?.length) bits.push(`blocks ${c.blocks.map(b => `~~${b}~~`).join(', ')}`);
    if (c.alters?.length) bits.push(`alters ${c.alters.map(a => `*${a}*`).join(', ')}`);
    if (bits.length) lines.push(`- choice **${c.label}**: ` + bits.join('; '));
  }
  if (!lines.length) continue;
  md += `## ${e.id} — ${e.title}\n*${e.type}${e.isElection ? ' / election' : ''}, ${e.yearWindow[0]}–${e.yearWindow[1]}*\n\n${lines.join('\n')}\n\n`;
}

// cross-reference matrix: who reads whose flags
const flagWriters = new Map();
for (const e of all) for (const c of e.choices || []) {
  for (const f of Object.keys(c.setsFlags || {})) {
    if (!flagWriters.has(f)) flagWriters.set(f, new Set());
    flagWriters.get(f).add(e.id);
  }
}
const flagReaders = new Map();
for (const e of all) {
  for (const r of [...(e.requires || []), ...(e.excludes || [])]) {
    const m = r.match(/^flag:(\w+)=/);
    if (m) {
      if (!flagReaders.has(m[1])) flagReaders.set(m[1], new Set());
      flagReaders.get(m[1]).add(e.id);
    }
  }
  // scorecard reads world flags too
  for (const c of e.choices || []) for (const f of Object.keys(c.setsFlags || {})) {
    if (!flagReaders.has(f)) flagReaders.set(f, new Set());
  }
}

md += `## Flag flow — writers → readers

| Flag | Set by | Read/gated by |
|---|---|---|
`;
for (const [flag, writers] of [...flagWriters].sort()) {
  const readers = [...(flagReaders.get(flag) || [])].filter(id => !writers.has(id));
  md += `| \`${flag}\` | ${[...writers].join(', ')} | ${readers.length ? readers.join(', ') : '*(scorecard only)*'} |\n`;
}

writeFileSync(new URL('../EVENT_GRAPH.md', import.meta.url), md);
console.log(`EVENT_GRAPH.md written: ${all.length} events, ${flagWriters.size} flags mapped.`);
