// V2-13 pack #3: Trade posture (6-7 events). Cultural exemption is first-class.
// Constraint: may SET tradePosture; shock-severity payoffs STUBBED (no "milder
// 2008" variants) until V2-10 eligibility model exists.

export const TRADE_PACK = [
  {
    id: 'FREE_TRADE_ANCHOR_1988',
    title: 'Free Trade with America',
    yearWindow: [1987, 1989],
    type: 'universal',
    actor: 'government',
    priority: 5,   // era-defining
    metricsAffected: ['economy', 'sovereign', 'unity', 'social'],
    context: 'A comprehensive free trade agreement with the United States is on the table: tariffs fall to zero over ten years, dispute settlement replaces American anti-dumping courts — and Canada\'s cultural industries are caught in the middle. Negotiators want magazines, film, and broadcasting fully covered. Canadian publishers and filmmakers say a tariff is the only wall between them and extinction.',
    choices: [
      {
        id: 'broad_culture',
        label: 'Sign broad agreement — culture included',
        desc: 'Maximum market access. Cultural industries compete like any other.',
        metrics: { economy: 4, sovereign: -6, social: -2 },
        setsFlags: { tradePosture: 'continental' },
        approvalDelta: 1,
        isHistorical: false,
      },
      {
        id: 'carveout_culture',
        label: 'Sign with a cultural exemption',
        desc: 'Tariffs fall, but books, film, and broadcasting stay protected as national identity.',
        metrics: { economy: 3, sovereign: -1, social: 2 },
        setsFlags: { tradePosture: 'continental', culturalExemption: true },
        isHistorical: true,
      },
      {
        id: 'no_deal',
        label: 'Walk away from the table',
        desc: 'No deal. Diversify trade elsewhere, keep all policy tools at home.',
        metrics: { economy: -2, sovereign: 4 },
        setsFlags: { tradePosture: 'diversified' },
        approvalDelta: -2,
        isHistorical: false,
      },
    ],
  },
  {
    id: 'NAFTA_EXTENSION_1993',
    title: 'Extending the Pact to Mexico',
    yearWindow: [1992, 1994],
    type: 'altered',
    actor: 'government',
    priority: 2,
    metricsAffected: ['economy', 'sovereign'],
    requires: [],  // altered by existing tradePosture
    context: 'The agreement can be extended into a three-country North American bloc. Business wants the bigger market; labour warns of a continental low-wage competition zone.',
    choices: [
      {
        id: 'join',
        label: 'Join the trilateral bloc',
        desc: 'Lock in access and investment rules across North America.',
        metrics: { economy: 3, sovereign: -2 },
        setsFlags: { tradePosture: 'continental' },
        isHistorical: true,
      },
      {
        id: 'stay_bilateral',
        label: 'Stay bilateral with Washington only',
        desc: 'Mexico\'s problems are not ours. Keep the existing deal.',
        metrics: { economy: 0, sovereign: 1 },
        approvalDelta: 0,
        isHistorical: false,
      },
      {
        id: 'renegotiate_diversify',
        label: 'Use the moment to diversify',
        desc: 'Open parallel talks with Europe and Asia instead of deepening continental ties.',
        metrics: { economy: -1, sovereign: 3 },
        setsFlags: { tradePosture: 'diversified' },
        approvalDelta: -1,
        isHistorical: false,
      },
    ],
  },
  {
    id: 'TRADE_CHINA_2014',
    title: 'The China Question',
    yearWindow: [2013, 2016],
    type: 'altered',
    actor: 'government',
    priority: 2,
    metricsAffected: ['economy', 'rights', 'sovereign'],
    context: 'Beijing offers expanded trade and investment talks: canola, timber, energy exports east. At the same time, human-rights groups press for a public reckoning with detentions and forced-labour allegations in Chinese supply chains. A foreign-investment takeover of a major Canadian resource company also awaits a national-security review.',
    choices: [
      {
        id: 'deepen',
        label: 'Deepen the relationship',
        desc: 'Pursue the trade deal; take the growth, accept the leverage Beijing gains.',
        metrics: { economy: 3, rights: -2, sovereign: -3 },
        setsFlags: { tradePosture: 'diversified', chinaExposure: 'deep' },
        isHistorical: true,
      },
      {
        id: 'conditional',
        label: 'Trade yes — with human-rights conditions',
        desc: 'Progress on the file, but supply-chain transparency rules and investment screening.',
        metrics: { economy: 1, rights: 2, sovereign: 0 },
        setsFlags: { chinaExposure: 'screened' },
        approvalDelta: 0,
        isHistorical: false,
      },
      {
        id: 'avoid',
        label: 'Keep Beijing at arm\'s length',
        desc: 'The values premium is real. No expansion deal.',
        metrics: { economy: -2, rights: 3, sovereign: 2 },
        setsFlags: { chinaExposure: 'low' },
        approvalDelta: -1,
        isHistorical: false,
      },
    ],
  },
  {
    id: 'TARIFF_SHOCK_2025',
    title: 'The Tariff Threat',
    yearWindow: [2024, 2026],
    type: 'reactive',
    actor: 'government',
    priority: 5,
    metricsAffected: ['economy', 'sovereign', 'unity'],
    // stub: severity scaling by tradePosture lands when V2-10 shock model exists;
    // for now copy acknowledges posture but effects are fixed
    context: 'Washington threatens sweeping tariffs on Canadian goods — cars, steel, aluminum, energy. Retaliation invites escalation; concession invites more demands. The threat tests every assumption about market access built since 1988.',
    choices: [
      {
        id: 'retaliate',
        label: 'Retaliate with matching tariffs',
        desc: 'Hit their states hard enough that Congress blinks. Accept the cost at home.',
        metrics: { economy: -4, sovereign: 4, unity: 1 },
        financial: { unemployment: 0.8, growthIndex: -5 },
        isHistorical: true,
      },
      {
        id: 'negotiate',
        label: 'Negotiate quietly — offer concessions',
        desc: 'Border commitments, procurement shifts, energy deals. Whatever keeps tariffs off.',
        metrics: { economy: -1, sovereign: -5 },
        financial: { unemployment: 0.2 },
        isHistorical: false,
      },
      {
        id: 'pivot_allies',
        label: 'Pivot to allies and internal trade',
        desc: 'Emergency diversification: Europe, Asia, and tearing down interprovincial barriers.',
        metrics: { economy: -3, sovereign: 2 },
        financial: { debtToGdp: 0.5 },
        setsFlags: { tradePosture: 'diversified' },
        approvalDelta: 0,
        isHistorical: false,
      },
    ],
  },
];
