// V2-13 pack #6: Crown sector (~5 events, aggregate crownSector posture flag).
// Consensus: NO per-asset sub-state, NO delayed-effects queue — consequences
// land as immediate deltas + alters: hooks on later trade/shock events.

export const CROWN_PACK = [
  {
    id: 'CROWN_EXPANSION_1976',
    title: 'The Crown Corporation Buildup',
    yearWindow: [1974, 1979],
    type: 'party',
    actor: 'government',
    priority: 2,
    metricsAffected: ['economy', 'social'],
    context: 'Public enterprise is ascendant: a national oil company to give Ottawa a window on the industry, nationalized passenger rail, regional airlines, state telecoms. Each new Crown comes with a minister, a mandate — and a patronage roster.',
    choices: [
      {
        id: 'expand',
        label: 'Expand the Crown sector aggressively',
        desc: 'New corporations for energy, transport, and development. The state as entrepreneur.',
        metrics: {social: 3, economy: -1, externalIndependence: 4, },
        financial: { debtToGdp: 1.0 },
        setsFlags: { crownSector: 'expansionist' },
        approvalDelta: 1,
        isHistorical: true,
      },
      {
        id: 'selective',
        label: 'Approve selectively with arm\'s-length boards',
        desc: 'Only where markets fail — and insulate the boards from ministers.',
        metrics: {social: 1, economy: 0, externalIndependence: 2, },
        setsFlags: { crownSector: 'mixed' },
        isHistorical: false,
      },
      {
        id: 'hold_private',
        label: 'Keep the state out of business',
        desc: 'Incentives and regulation instead of ownership.',
        metrics: {economy: 2, externalIndependence: -3, },
        setsFlags: { crownSector: 'retrenchment' },
        approvalDelta: -1,
        isHistorical: false,
      },
    ],
  },
  {
    id: 'VIA_RAIL_1978',
    title: 'The Future of Passenger Rail',
    yearWindow: [1977, 1981],
    type: 'universal',
    actor: 'government',
    priority: 1,
    metricsAffected: ['social', 'economy'],
    context: 'Passenger trains are losing money at a spectacular rate. CN wants out; VIA Rail can be created as a dedicated Crown to run them — or the routes can be cut back to the few that pay.',
    choices: [
      {
        id: 'create_via',
        label: 'Create VIA Rail',
        desc: 'A public passenger rail company with a national network mandate.',
        metrics: {social: 3, economy: -1, externalIndependence: 1, },
        financial: { debtToGdp: 0.2 },
        setsFlags: { crownSector: 'expansionist' },
        isHistorical: true,
      },
      {
        id: 'cut_routes',
        label: 'Cut routes to the viable core',
        desc: 'Keep the corridor trains; let long-haul service go.',
        metrics: { social: -2, economy: 1 },
        setsFlags: { crownSector: 'retrenchment' },
        isHistorical: false,
      },
    ],
  },
  {
    id: 'CROWN_PRIVATIZATION_1985',
    title: 'Selling the Family Silver',
    yearWindow: [1984, 1990],
    type: 'altered',
    actor: 'government',
    priority: 3,
    metricsAffected: ['economy', 'social'],
    requires: [],   // altered by existing crownSector posture
    context: 'Debt is high and privatization is the fashion in Washington and London. De Havilland, Canadair, Air Canada, Petro-Canada — each sale pays down debt and each one removes a lever of national policy. Canadians feel ownership of some of these companies in a way balance sheets cannot capture.',
    choices: [
      {
        id: 'sell_wave',
        label: 'Sell the major Crowns',
        desc: 'Air Canada, de Havilland, Canadair — and shrink Petro-Canada\'s role.',
        metrics: {economy: 4, social: -3, externalIndependence: -5, },
        financial: { debtToGdp: -3.0 },
        setsFlags: { crownSector: 'retrenchment' },
        isHistorical: true,
      },
      {
        id: 'sell_some',
        label: 'Sell the failing ones only',
        desc: 'De Havilland and Canadair bleed money; Air Canada and Petro-Canada stay public.',
        metrics: {economy: 1, social: -1, externalIndependence: -1, },
        financial: { debtToGdp: -1.0 },
        setsFlags: { crownSector: 'mixed' },
        isHistorical: false,
      },
      {
        id: 'keep_all',
        label: 'Keep them all — fix governance instead',
        desc: 'Arm\'s-length boards, performance mandates, no ministerial meddling.',
        metrics: {economy: -1, rights: 2, externalIndependence: 2, },
        setsFlags: { crownSector: 'expansionist', institutionalTrust: 'reformed' },
        approvalDelta: 0,
        isHistorical: false,
      },
    ],
  },
  {
    id: 'PETRO_CAN_1991',
    title: 'The Future of Petro-Canada',
    yearWindow: [1990, 1993],
    type: 'altered',
    actor: 'government',
    priority: 2,
    metricsAffected: ['economy'],
    requires: [],   // altered by energyModel from NEP pack
    context: 'The national oil company was born of the NEP fight. With fiscal crisis pressing, its full or partial sale could raise billions — or it can remain the national window into a strategic industry.',
    choices: [
      {
        id: 'full_sale',
        label: 'Privatize fully',
        desc: 'Sell shares to the public. The era of national champion oil ends.',
        metrics: {economy: 2, externalIndependence: -4, },
        financial: { debtToGdp: -2.5 },
        setsFlags: { crownSector: 'retrenchment' },
        isHistorical: true,
      },
      {
        id: 'partial',
        label: 'Partial float — keep the golden share',
        desc: 'Raise revenue while preserving federal control over strategy.',
        metrics: {economy: 1, externalIndependence: -1, },
        financial: { debtToGdp: -1.2 },
        setsFlags: { crownSector: 'mixed' },
        isHistorical: false,
      },
      {
        id: 'keep_public',
        label: 'Keep it fully public',
        desc: 'Strategic control is worth more than the proceeds.',
        metrics: {economy: -1, externalIndependence: 3, },
        financial: { debtToGdp: 0 },
        setsFlags: { crownSector: 'expansionist' },
        approvalDelta: -1,
        isHistorical: false,
      },
    ],
  },
];
